# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Introduction to Machine Learning
subtitle: 10-701, Fall 2020
description: >-
  This course is designed to give PhD students a thorough grounding in the
  methods, theory, mathematics and algorithms needed to do research and
  applications in machine learning. The topics of the course draw from from
  machine learning, from classical statistics, from data mining, from Bayesian
  statistics and from information theory.
baseurl: "/~epxing/Class/10701-20"
url: "https://www.cs.cmu.edu"

# Build settings
theme: "just-the-docs"

exclude:
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-seo-tag

search_enabled: false
